apiVersion: v2
name: webserver-simple-staging-us
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: webserver-simple
    version: 1.0.0
    repository: file://../webserver-simple
