env:
  - name: UI_THEME
    value: dark
  - name: CACHE_SIZE
    value: 1024kb
  - name: PAGE_LIMIT
    value: "25"
  - name: SORTING
    value: ascending
  - name: N_BUCKETS
    value: "42"
  - name: ENV
    value: prod-us
  - name: GPU_ENABLED
    value: "1"
  - name: REGION
    value: us
  - name: ENV_TYPE
    value: production
  - name: PAYPAL_URL
    value: production.paypal.com
  - name: DB_USER
    value: prod_username
  - name: DB_PASSWORD
    value: prod_password

replicaCount: 8

fullnameOverride: prod-us-simple

nodeSelector: {}